[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Linux System

## index/search data
> mmd.emoticon=`asterisk`


### krunner

### rofi

### fish/bash history sugggestion

## shell
> topicLinkUID=`185F4310FDAA`

- NOTE
<pre>wow, see this is a note
</pre>

### fish

#### omf

### bash

## information displays
> leftSide=`true`


## hotkey navigation
> leftSide=`true`


## cheat

## utilities
